# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_playbook: jupyterhub.yml
- import_playbook: livy.yml
- import_playbook: livy-spark3.yml
- import_playbook: zookeeper-kafka.yml
- import_playbook: kafka.yml
- import_playbook: airflow.yml
