# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure Jupyterhub Server
  hosts: jupyterhub_server
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: jupyterhub_server
    - name: Configure Jupyterhub Server
      ansible.builtin.import_role:
        name: tosit.tdp_extra.jupyterhub.server
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
